---
spring:
  application:
    name: "gateway"
  cloud:
    gateway:
      routes:
      - id: "first_service"
        uri: "http://localhost:8081"
        predicates:
        - "Path=/first/**"
      - id: "second_service"
        uri: "http://localhost:8081"
        predicates:
        - "Path=/second/**"
      - id: "aTob_service"
        uri: "http://localhost:8081"
        predicates:
        - "Path=/first/a"
        filters:
        - "SetPath=/second/b"
      - id: "third_service"
        uri: "http://localhost:8081"
        predicates:
        - "Path=/third/*"

management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include:
        - "*"
resilience4j:
  circuitbreaker:
    configs:
      default:
        ringBufferSizeInClosedState: 10
        ringBufferSizeInHalfOpenState: 30
        failureRateThreshold: 80
        waitDurationInOpenState: "10s"
